spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.97:3306/mdl_vip?useTimezone=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Pan123456!
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 2000
      max-wait: 60000
  redis:
    port: 6379
    database: 0
    connect-timeout: 60s
    jedis:
      pool:
        min-idle: 100
        max-idle: 1000
        max-wait: 30000
        max-active: 256
    timeout: 30s
    host: 192.168.31.97
    password: Pan123630
  rabbitmq:
    host: 192.168.31.97
    port: 5672
    username: admin
    password: admin123
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者，每次只能处理一条消息，处理完才能继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认为 true
        auto-startup: true
        #被拒绝时重新进入队列的
        default-requeue-rejected: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rxvip.core.dao.*.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#  global-config:
#    db-config:
#      id-type: assign_id  #主键策略 使用雪花算法
wx:
  pusher:
    url: https://wxpusher.zjiecode.com/api/send/message
    appToken: AT_fxwcBYarh32hWZNQ6LVfX6pKeR1CDprs
    uid: UID_bOA6eLSDpvlrhX9isl4ucEMvS0dm,UID_L1lFqLQP0H10wl2gXzwaK3EMRcdW
pay:
  url: http://pay.mdlvip.top

generateLink:
  userName: c776899
  password: 98jqam